import { establishPrimitive } from "./slopkit/core.js";
import { abortPrimitive, cleanupTemporaryAllocations } from "./slopkit/core.js";
import { installWindowP } from "./slopkit/mem.js";
import { BUILD_ID, createResearchState } from "./research-state.js";
import { createDiagnosticsBridge } from "./diagnostics-bridge.js";
import { create1302ResearchAdapter } from "./research-adapter.js";
import { createObservationUi } from "./observation-ui.js";
function parseQuery(name){const pairs=(location.search||"").replace(/^\?/,"").split("&");for(let i=0;i<pairs.length;i++){const p=pairs[i].split("=");if(decodeURIComponent(p[0]||"")===name)return decodeURIComponent((p[1]||"").replace(/\+/g," "));}return "";}
function isResearchFirmware(value){const m=/^(\d+)\.(\d{2})$/.exec(String(value||""));if(!m)return false;const n=parseInt(m[1],10)*100+parseInt(m[2],10);return n>=1302&&n<=1352;}
function detectRuntimeContext(){const m=/PlayStation\s+4[\/ ](\d+)\.(\d+)/.exec(navigator.userAgent||""),forced=(parseQuery("fw")||"").replace(/\s+/g,"").trim(),researchMode=parseQuery("research")==="1",simulated=isResearchFirmware(forced)&&researchMode;if(m){const minorValue=parseInt(m[2],16);let minor=minorValue.toString(16);if(minor.length<2)minor="0"+minor;const firmware=m[1]+"."+minor;return{firmware,firmwareSource:"UA",hardwareDetected:true,researchFirmware:isResearchFirmware(firmware),simulated:false,researchMode};}return{firmware:forced||(simulated?"13.02":"Unknown"),firmwareSource:forced?"QUERY":"UNKNOWN",hardwareDetected:false,researchFirmware:false,simulated,researchMode};}
function hasWindowP(prim){return !!(prim&&typeof prim.read1==="function"&&typeof prim.read2==="function"&&typeof prim.read4==="function"&&typeof prim.read8==="function"&&typeof prim.write1==="function"&&typeof prim.write2==="function"&&typeof prim.write4==="function"&&typeof prim.write8==="function"&&typeof prim.leakval==="function");}
function readVerified(carrier,prim){if(!carrier||!prim||typeof prim.read1!=="function")return false;try{return !!carrier.assertHome()&&typeof prim.read1(carrier.hostAddress)==="number";}catch(e){return false;}}
function writeVerified(carrier){if(!carrier||typeof carrier.aim!=="function"||!carrier.view)return false;try{carrier.aim(carrier.hostAddress);const original=carrier.view[0],mutated=original^1;carrier.view[0]=mutated;const wrote=carrier.view[0]===mutated;carrier.view[0]=original;const restored=carrier.view[0]===original;carrier.restore();return !!carrier.assertHome()&&wrote&&restored;}catch(e){try{carrier.restore();}catch(x){}return false;}}
const doc=document,state=createResearchState(doc),diagnostics=createDiagnosticsBridge(state),runButton=doc.getElementById("run-test"),stopButton=doc.getElementById("stop-test"),downloadButton=doc.getElementById("download-report"),context=detectRuntimeContext();
let adapter=createAdapter("");
function createAdapter(sessionId){return create1302ResearchAdapter({firmware:context.firmware,sessionId,entryMethod:"SlopKit",diagnostics,primitiveFactory:establishPrimitive,installWindowP,hasWindowP,verifyRead:readVerified,verifyWrite:writeVerified,abortPrimitive,releaseTemporaryAllocations:cleanupTemporaryAllocations,onPrimitiveEvent:function(tag,detail,attempt){diagnostics.emit(tag,detail,{attempt,sessionId:state.snapshot.sessionId});}});}
state.setFirmware(context.firmware==="Unknown"?"Unknown":context.firmware,context.firmwareSource);state.setSimulation(context.simulated);state.setHardware(context.simulated?"simulation":context.researchFirmware?"hardware":"outside-13.02-13.52");state.setHen("none","No HEN","none",null,null,"source-confirmed",false,false,"LOCKED","HEN loading is locked during the 13.02-13.52 userland research test.");
if(context.simulated){state.setHardwareTest("READY","Simulation mode is enabled for UI and diagnostics testing only.");state.setStatus("Simulation mode is enabled for page and diagnostics testing only.");}else if(context.researchFirmware){state.setHardwareTest("READY","Hardware firmware matches. Manual SlopKit test available.");state.setStatus("Awaiting manual start.");}else{state.setHardwareTest("LOCKED","This console is outside the 13.02-13.52 research range.");state.setStatus("NEXT 13.02-13.52 Research Laboratory loaded for inspection only. Execution is locked outside the supported research range.","bad");runButton.disabled=true;}
const observationUi=createObservationUi(doc,state);
diagnostics.init();adapter.initialize();observationUi.refresh();
window.addEventListener("error",e=>state.setJsError(e&&e.message?e.message:"JavaScript error"));window.addEventListener("beforeunload",()=>{if(state.snapshot.running){state.setUnexpectedTermination("page-unloaded-while-running");diagnostics.markCompleted(false);}});
function finishRun(sessionId,success,detail){diagnostics.emit("NEXT-1302-SESSION-COMPLETED",detail||String(success?"success":"failed"),{sessionId});state.setRunning(false);diagnostics.markCompleted(!!success);observationUi.refresh();}
async function runProbe(){let entryResult,verifyResult;state.clearStopRequest();const sessionId=state.beginSession();adapter=createAdapter(sessionId);adapter.initialize();state.setRunning(true);state.setStatus("Starting isolated SlopKit userland probe. Session "+sessionId);state.setPrimitive("NOT TESTED");state.setCarrier("NOT OBTAINED",false);state.setWindowP("NOT INSTALLED",false);state.setRead("NOT VERIFIED",false);state.setWrite("NOT VERIFIED",false);state.setARW("NOT VERIFIED",false);observationUi.refresh();diagnostics.markRunning();diagnostics.emit("NEXT-1302-BOOT","build="+BUILD_ID,{sessionId});if(context.simulated){state.setStatus("Simulation mode does not execute SlopKit. UI and diagnostics only.","bad");diagnostics.emit("SLOPKIT-FAIL","simulation-only-page-ui-test",{sessionId});finishRun(sessionId,false,"simulation-only");return;}if(!context.researchFirmware){state.setStatus("This page only accepts PS4 firmware 13.02 through 13.52 hardware.","bad");diagnostics.emit("SLOPKIT-FAIL","requires-ps4-13.02-through-13.52-hardware",{sessionId});finishRun(sessionId,false,"unsupported-hardware");return;}diagnostics.emit("NEXT-1302-HARDWARE-CONFIRMED",navigator.userAgent,{sessionId});diagnostics.emit("SLOPKIT-BEGIN","maxAttempts=6",{sessionId});state.setPrimitive("RUNNING");entryResult=await adapter.runUserlandEntry();if(!entryResult||!entryResult.ok){state.setPrimitive("FAILED");state.setStatus("SlopKit did not complete a verified entry stage.","bad");finishRun(sessionId,false,"entry-not-verified");return;}if(state.snapshot.stopRequested){state.setStatus("Stop requested. Probe halted before validation.","bad");finishRun(sessionId,false,"stop-requested");return;}state.setPrimitive("OBTAINED");state.setCarrier("OBTAINED",true);state.setWindowP("INSTALLED",true);diagnostics.emit("SLOPKIT-CARRIER-OBTAINED","carrier-returned",{sessionId});diagnostics.emit("SLOPKIT-WINDOW-P-INSTALLED","promote=false",{sessionId});verifyResult=await adapter.verifyUserlandReadWrite();if(!verifyResult||!verifyResult.ok){state.setStatus("Userland read/write could not be verified.","bad");finishRun(sessionId,false,"userland-read-write-not-verified");return;}state.setRead("VERIFIED",true);state.setWrite("VERIFIED",true);diagnostics.emit("SLOPKIT-READ-VERIFIED","carrier-self-validation-pass",{sessionId});diagnostics.emit("SLOPKIT-WRITE-VERIFIED","page-owned-memory-restored",{sessionId});state.setARW("VERIFIED",true);state.setStatus(context.firmware+" userland validation completed. Kernel path remains locked. Session "+sessionId,"ok");diagnostics.emit("USERLAND-ARW-VERIFIED","read-and-write-verified",{sessionId});finishRun(sessionId,true,"userland-validation-completed");}
runButton.addEventListener("click",()=>{if(!state.snapshot.running)runProbe().catch(error=>{state.setJsError(error&&error.message?error.message:String(error));const sessionId=state.snapshot.sessionId;state.setStatus("Research run stopped by a JavaScript error.","bad");if(sessionId)finishRun(sessionId,false,"unhandled-run-error");});});stopButton.addEventListener("click",()=>{state.requestStop();adapter.abort();state.setStatus(state.snapshot.running?"Stop requested. Waiting for the current SlopKit attempt to return.":"No active test is running.",state.snapshot.running?"bad":undefined);});downloadButton.addEventListener("click",()=>diagnostics.downloadReport());